<?php
/**
 * Created by PhpStorm.
 * User     : zhao
 * Date     : 2018/6/27
 * Time     : 13:37
 * Content  :
 */
namespace app\admin\controller;

class Contract extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return $this->fetch();
    }
}